version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run: |
          echo $GOOGLE_SERVICES | base64 --decode > ~/code/app/google-services.json
          export TERM=${TERM:-dumb} && ./gradlew clean build --recompile-scripts --refresh-dependencies --parallel --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: artifact-file
